import banach_algebras_differentiable_analytic_functions_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace banach_algebras_differentiable_analytic_functions_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end banach_algebras_differentiable_analytic_functions_lemma_canonical_lane_mathlib
end HautevilleHouse
